# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sawa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_terrible', models.IntegerField()),
                ('ct_bad', models.IntegerField()),
                ('ct_neutral', models.IntegerField()),
                ('ct_good', models.IntegerField()),
                ('ct_excellent', models.IntegerField()),
            ],
        ),
    ]
